### ISSUE TITLE
does not detect the PQR hack

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/mod-anticheat#105]
### Current Behaviour

does not detect the PQR hack, this allows the player's pj to do automatic rotations without touching anything

### Expected Blizzlike Behaviour

does not detect the PQR hack, this allows the player's pj to do automatic rotations without touching anything

### Source

https://github.com/darhanger/PQR_DarhangeR_3.3.5a

### Steps to reproduce the problem

download the PQR run wow and configure the PQR to use the hack

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/539801377fb96f2c3377e051fa9264315501fd1e

### Operating system

Ubuntu 20.04

**Comment by Tony931023** [comment]
@acidmanifesto when you can check this

**Comment by acidmanifesto** [comment]
At the moment this is not really a case for the passive anticheat.
Would be better suited in reporting it as a bug as there was a warden pr that was put in some time ago that addressed the issue supposively.
https://github.com/azerothcore/azerothcore-wotlk/pull/3875
