### ISSUE TITLE
The Kael'thas Sunstrider cast spell let palyers up to sky,all players will report cheat.

### ISSUE THREAD

**Issue by kissingers** [azerothcore/mod-anticheat#106]
### Current Behaviour

.go 19622
try fight with the boss till player up to sky.  the player will report antcheat.

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

N/A

### AC rev. hash/commit

N/A

### Operating system

debian 11 x64

**Comment by acidmanifesto** [comment]
Do you have any anticheat logs to provide?
And spells or auras on the player when they are false flagged?

**Comment by acidmanifesto** [comment]
Are we talking about this spell?
https://www.wowhead.com/spell=44224/gravity-lapse#comments

**Comment by kissingers** [comment]
> Are we talking about this spell? https://www.wowhead.com/spell=44224/gravity-lapse#comments
Yes. when to 50% will up hit the case, but only those who up to very high player.
I close the DetectZaxisHack and  DetectJumpHack, still have the problem,  so maybe cased by DetectClimbHack, I close it , but not check  after, I will test later with our friends and feed back.

**Comment by acidmanifesto** [comment]
> .go 19622
> try fight with the boss till player up to sky. the player will report antcheat.
Can you double check that gm cmd? I am getting sent ot a giant bird.

**Comment by acidmanifesto** [comment]
So the correct cmd is .go c 96762
I have no clue where .go 19622 came from.

ok. so i went ahead and tested. I am not getting any false hits at all. Please ensure both your core and anticheat module is up to date and not modified. At this point it is unfounded and can not be reproduced. If you are able to reproduce it please include auras that are showing on the player and also provide the anticheat.log files.

![image](https://user-images.githubusercontent.com/16887899/233857564-47509138-ce1a-4d4a-9ee7-0e64edc74074.png)
