### ISSUE TITLE
Sindragosa attract and cast virulent cold False Hit with hack detection

### ISSUE THREAD

**Issue by Fireevil** [azerothcore/mod-anticheat#107]
### Current Behaviour

Sindragosa attract

### Expected Blizzlike Behaviour

.

### Steps to reproduce the problem

.

### Extra Notes

.

### AC rev. hash/commit

.

### Operating system

windows 10

**Comment by acidmanifesto** [comment]
> ### Current Behaviour
> 
> Sindragosa attract
> 
> ### Expected Blizzlike Behaviour
> 
> .
> 
> ### Source
> 
> _No response_
> 
> ### Steps to reproduce the problem
> 
> .
> 
> ### Extra Notes
> 
> .
> 
> ### AC rev. hash/commit
> 
> .
> 
> ### Operating system
> 
> windows 10
> 
> ### Custom changes or Modules
> 
> _No response_

This tells me absolutely nothing at all.
What is the cordinates? What is the guid or npc entry id?
What cheats is being detected?
Where is the anticheat.logs?
