### ISSUE TITLE
Feature: Table 'acore_characters.daily_players_reports' doesn't exist

### ISSUE THREAD

**Issue by stefan3126** [azerothcore/mod-anticheat#108]
### Describe your feature request or suggestion in detail

ERROR 1146 (42S02) at line 19 in file: 'D:\azerothcore-wotlk-master\modules\mod-anticheat\sql\updates\characters\AC_2022_08_12_00.sql': Table 'acore_characters.daily_players_reports' doesn't exist
Applying of file 'D:/azerothcore-wotlk-master/modules/mod-anticheat/sql/updates/characters/AC_2022_08_12_00.sql' to database 'acore_characters' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from AzerothCore repository with your sql client. If you are a developer, please fix your sql query.

**Comment by acidmanifesto** [comment]
Run the characters sql on the character db and world sqls on the world db first.
https://github.com/azerothcore/mod-anticheat/tree/master/sql

Ignore the update folder. Recompile and restsrt the server and it should auto update the rest.

**Comment by acidmanifesto** [comment]
> When run the Acore_strings.sql  on the world db ：
> 
> \n\r\nDeletes stored statistics of daily_players_reports table.'),
> ('anticheat warn', 2, 'Syntax: .anticheat warn [$charactername]\r\n\r\nSends individual player they are being monitored for possible cheating.');
> [Msg] Finished - Unsuccessfully

I am not entirely certain here. Are u running the whole file or partial? What sql editor are you using?

**Comment by acidmanifesto** [comment]
Well you need the sql applied. I however am not encountering that issue unless there is some sort of strict setting with navicat that disallows deletes to be ran on none exsistent queries as that is the standard to be rerunable. Try running the inserts only on the world from the acore_strings and ensure you run the character on the character db as well.
