### ISSUE TITLE
Problem with latest build AzerothCore rev. 17069cc63898+ 2019-03-07 21:22:54 +0000 (master branch)

### ISSUE THREAD

**Issue by Nemepy** [azerothcore/mod-anticheat#12]
/wowlanpy/azerothcore/modules/mod-anticheat/src/AnticheatMgr.cpp: In member function ‘void AnticheatMgr::WalkOnWaterHackDetection(Player*, MovementInfo)’:
/wowlanpy/azerothcore/modules/mod-anticheat/src/AnticheatMgr.cpp:68:40: error: no matching function for call to ‘WorldSession::KickPlayer(bool)’
   player->GetSession()->KickPlayer(true);
                                        ^
In file included from /wowlanpy/azerothcore/src/server/game/Entities/Player/Player.h:21:0,
                 from /wowlanpy/azerothcore/src/server/game/Grids/Notifiers/GridNotifiers.h:18,
                 from PrecompiledHeaders/ScriptPCH.h:13:
/wowlanpy/azerothcore/src/server/game/Server/WorldSession.h:250:14: note: candidate: void WorldSession::KickPlayer(const string&, bool)
         void KickPlayer(std::string const& reason, bool setKicked = true);
              ^~~~~~~~~~
/wowlanpy/azerothcore/src/server/game/Server/WorldSession.h:250:14: note:   no known conversion for argument 1 from ‘bool’ to ‘const string& {aka const std::__cxx11::basic_string<char>&}’
/wowlanpy/azerothcore/modules/mod-anticheat/src/AnticheatMgr.cpp: In member function ‘void AnticheatMgr::FlyHackDetection(Player*, MovementInfo)’:
/wowlanpy/azerothcore/modules/mod-anticheat/src/AnticheatMgr.cpp:99:40: error: no matching function for call to ‘WorldSession::KickPlayer(bool)’
   player->GetSession()->KickPlayer(true);
                                        ^
In file included from /wowlanpy/azerothcore/src/server/game/Entities/Player/Player.h:21:0,
                 from /wowlanpy/azerothcore/src/server/game/Grids/Notifiers/GridNotifiers.h:18,
                 from PrecompiledHeaders/ScriptPCH.h:13:
/wowlanpy/azerothcore/src/server/game/Server/WorldSession.h:250:14: note: candidate: void WorldSession::KickPlayer(const string&, bool)
         void KickPlayer(std::string const& reason, bool setKicked = true);
              ^~~~~~~~~~
/wowlanpy/azerothcore/src/server/game/Server/WorldSession.h:250:14: note:   no known conversion for argument 1 from ‘bool’ to ‘const string& {aka const std::__cxx11::basic_string<char>&}’
[ 99%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-anticheat/src/AnticheatScripts.cpp.o
[ 99%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-anticheat/src/AnticheatData.cpp.o
[ 99%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-anticheat/src/cs_anticheat.cpp.o
src/server/scripts/CMakeFiles/scripts.dir/build.make:13358: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-anticheat/src/AnticheatMgr.cpp.o' failed
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-anticheat/src/AnticheatMgr.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1296: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/all' failed
make[1]: *** [src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by OnionSNS** [comment]
feat(core): allow to debug KickPlayer() (#1549)

**Comment by OnionSNS** [comment]
> feat（核心）：允许调试KickPlayer（）（＃1549）

\azerothcore-wotlk\modules\mod-anticheat\src\AnticheatMgr.cpp

		player->GetSession()->KickPlayer("KickFlyHack", true);
		player->GetSession()->KickPlayer("KickWalkHack", true);

**Comment by milestorme** [comment]
I have the same issue , apply that change and get 
Error	C2664	'void WorldSession::KickPlayer(const std::string &,bool)': cannot convert argument 1 from 'bool' to 'const std::string &'	scripts	C:\AzerothCore\azerothcore-wotlk-ahbot\modules\mod-anticheat\src\AnticheatMgr.cpp	100	

do the same at line 100

**Comment by milestorme** [comment]
resolved in latest AzerothCore master commit 048eddd  fixed by FrancescoBorzi authored and Deku committed 17 minutes ago will work as it did before now

**Comment by BarbzYHOOL** [comment]
ty milestorme for info
