### ISSUE TITLE
Don't Work Anticheat - AC

### ISSUE THREAD

**Issue by wowmane** [azerothcore/mod-anticheat#16]
Hi @BarbzYHOOL

Please updated Anticheat, i use this anticheat module But all can to use cheat hacks, speed and fly !

**Comment by poszer** [comment]
Already reported. Closing

**Comment by Winfidonarleyan** [comment]
Hah, lol, the description is BEST!

**Comment by saltyzero** [comment]
I have detected their memory hack in my repack.

**Comment by BarbzYHOOL** [comment]
Check this: https://github.com/azerothcore/azerothcore-wotlk/pull/2088 and test it
