### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by dev-master21** [azerothcore/mod-anticheat#18]
![image](https://user-images.githubusercontent.com/16816228/68993987-c7a10280-08a7-11ea-9249-c13ea7cd1e0d.png)

**Comment by th3lolipop** [comment]
i got the same issue with docker environment @FrancescoBorzi

**Comment by Helias** [comment]
Fixed by https://github.com/azerothcore/mod-anticheat/pull/19
Thanks @dev-master21 and @th3lolipop for report this.

**Comment by th3lolipop** [comment]
Thanks @Helias.
I have another issue with this module or may be i don't how does it works :/

**THE PROBLEM**

> Anticheat.Enabled = 1
> Anticheat.KickPlayerFlyHack = 1
> Anticheat.KickPlayerWaterWalkHack = 1

I set there values in configuration file.
It didn't kick when player using cheating software ( I tested with "The Hitchhiker's Hack )
and the docker-compose log showing this all the time.

`ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
ac-worldserver_1  | -> Not found option 'Anticheat.Enabled'. The default value is used (No)
`

**Comment by Helias** [comment]
did you put the .conf files in the etc/ directory?
is this files with the right permissions?

what OS are you using?

**Comment by th3lolipop** [comment]
**Operating System**

Ubuntu 18.04.4 LTS

Sorry @Helias I just skipped the optional step :) 
Thank you brother

**Comment by Helias** [comment]
ok, perfect :+1: 
Anyway I use ubuntu 18.04 LTS too :+1:
