### ISSUE TITLE
What works and what doesn't

### ISSUE THREAD

**Issue by falzard** [azerothcore/mod-anticheat#2]
**Detected:**

1. Fly hack
2. Speed hack
3. If you "stop falling" and then you jump in the air, it detects **one** jumphack (not very useful)

**Undetected:**

1. Teleporting everywhere (behind target, undermap, or any zone)
2. Climb hack even when enabled in the AntiCheat.conf
3. No clip (going under the map)

**Couldn't test (no tool for that):**

1. Teleplane (wtf is that)
2. Waterwalk
3. Double jump

**Comment by acidmanifesto** [comment]
> **Undetected:**
> 
> 1. Teleporting everywhere (behind target, undermap, or any zone)

Now Detected [3bd91e1](https://github.com/azerothcore/mod-anticheat/commit/3bd91e16c4515543817896ded8098ac7bb45bcd3)

> 2. Climb hack even when enabled in the AntiCheat.conf

Now Detected [3bd91e1](https://github.com/azerothcore/mod-anticheat/commit/3bd91e16c4515543817896ded8098ac7bb45bcd3)

> 3. No clip (going under the map)

hits as teleport at times. not 100% detected at the moment

> **Couldn't test (no tool for that):**
> 
> 1. Teleplane (wtf is that)

Now Detected [3bd91e1](https://github.com/azerothcore/mod-anticheat/commit/3bd91e16c4515543817896ded8098ac7bb45bcd3)

> 2. Waterwalk

Now Detected [3bd91e1](https://github.com/azerothcore/mod-anticheat/commit/3bd91e16c4515543817896ded8098ac7bb45bcd3)

> 3. Double jump

Now Detected [3bd91e1](https://github.com/azerothcore/mod-anticheat/commit/3bd91e16c4515543817896ded8098ac7bb45bcd3)
