### ISSUE TITLE
use ".pinfo" command,server crash

### ISSUE THREAD

**Issue by mpfans** [azerothcore/mod-anticheat#24]
when GM uses the. pinfo command, the server crash...

 AzerothCore revision            : 4cb0c9fc0042+ 2020-12-10 05:57:54 +0000 (master branch)
OS:ubuntu 18.04
Module:mod-anticheat

**Comment by FrancescoBorzi** [comment]
thanks @mpfans for your feedback, moving to the right repository

**Comment by Helias** [comment]
cannot reproduce on 2e6f78bdddbc84a1950aaec0865a689efa9fcde4

**Comment by mpfans** [comment]
anticheat :https://github.com/azerothcore/mod-anticheat/commit/10659d66423ad11e3f0761f0d1fe36f988568110  
ac core :877e394e04e13662554f8cce663bea1c646a98d2

Still crash....

**Comment by mpfans** [comment]
@Helias

**Comment by acidmanifesto** [comment]
issue is no longer occuring with current revision being tested [3bd91e1](https://github.com/azerothcore/mod-anticheat/commit/3bd91e16c4515543817896ded8098ac7bb45bcd3)
