### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mpfans** [azerothcore/mod-anticheat#28]
update to azerothcore/azerothcore-wotlk@dbefa17
Compilation error
error log:
`/home/azerothcore/azerothcore/modules/mod-anticheat-master/src/AnticheatScripts.cpp:66:16: fatal error: no member named 'LoadMore' in 'ConfigMgr'`
                        `sConfigMgr->LoadMore(cfg_def_file.c_str());`

ubuntu 18.04
AC commit :dbefa17a534500522a174e9906d8923445c16e79

**Comment by luolingjun** [comment]
核心修改了 https://github.com/azerothcore/azerothcore-wotlk/commit/dbefa17a534500522a174e9906d8923445c16e79
azerothcore-wotlk/src/common/Configuration/Config.cpp

**Comment by Helias** [comment]
fixed here https://github.com/azerothcore/mod-anticheat/pull/29
