### ISSUE TITLE
Testing on anti - plug - in problem

### ISSUE THREAD

**Issue by ss958** [azerothcore/mod-anticheat#3]
1, stone conveyor has not been added to the exception function, will still be determined to be SpeedHack.
2 and TelePlaneHack test is invalid, will be judged as SpeedHack.
3, proposed: detected after the plug-in kicked out of the game, you do not have titles

**Comment by acidmanifesto** [comment]
please reopen issue if issue still presist with version [3bd91e1](https://github.com/azerothcore/mod-anticheat/commit/3bd91e16c4515543817896ded8098ac7bb45bcd3)
