### ISSUE TITLE
Hack Telport  Does not take

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/mod-anticheat#33]
![image](https://user-images.githubusercontent.com/80007195/119826295-1bfd5780-bf0d-11eb-9c83-efa366324b42.png)
![WoWScrnShot_052721_165338](https://user-images.githubusercontent.com/80007195/119826321-23bcfc00-bf0d-11eb-957f-1a7a704b8e82.jpg)

**Comment by acidmanifesto** [comment]
Teleport Hack detection is working now.
