### ISSUE TITLE
Does the /sql/world/Acore_strings.sql file need to be imported?

### ISSUE THREAD

**Issue by adink1** [azerothcore/mod-anticheat#51]
Does the /sql/world/Acore_strings.sql file need to be imported?

**Comment by acidmanifesto** [comment]
Yes

**Comment by acidmanifesto** [comment]
![Screenshot_20220311-202312_GitHub.jpg](https://user-images.githubusercontent.com/16887899/157998000-3e2cdc50-259b-4521-b94e-9cb12934ccbd.jpg)
