### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/mod-anticheat#55]
### when you are sent to jail and use teleport to get out. when using it about 5 times fast it makes this crash**

```
AnticheatMgr:: Walk on Water - Hack detected player Drakiron (GUID Full: 0x0000000000000023 Type: Player Low: 35)
AnticheatMgr:: Speed-Hack detected player Senarius (GUID Full: 0x0000000000000075 Type: Player Low: 117)
AnticheatMgr:: Teleport-Hack detected player Senarius (GUID Full: 0x0000000000000075 Type: Player Low: 117)
AnticheatMgr:: Reports reached assigned threshhold and counteracted by jailing player Senarius (GUID Full: 0x0000000000000075 Type: Player Low: 117)
#----------------------------------------------------------------------#

>> ASSERTION FAILED

# Location '/mnt/hdd/azerothcore/src/server/game/Entities/Object/Object.h:324'
# Function 'RemoveFromGrid'
# Condition 'IsInGrid()'

#----------------------------------------------------------------------#
Segmentation fault (core dumped)

```

**Comment by Tony931023** [comment]
@acidmanifesto This is serious, what could be done about it?

**Comment by Tony931023** [comment]
one of the mistakes is when he enters the jail he dies, he can use easy teleport and walk around the island of the gm

**Comment by acidmanifesto** [comment]
i need more details about the dying part, what the level of the character?, now as for the crashing, you need to know how teleporting hacks work, it is a memory offset, it will adjust the x y z o but never the mapid. so when you teleport to insane teleport location and it exceeds the grid, it will crash, we have no suffer that issue on cc as we use a combination of warden protection and lua intergration. which the list of lua modules is listed here - [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

Now as for the crash, is it only happening from gm island jail?

**Comment by Tony931023** [comment]
the player is level 80, if it only happens when you are sent to jail and you escape from there with teleport

**Comment by acidmanifesto** [comment]
what was the teleport location you were attempting to goto from the jail?
Was the automatic moderation for jail active?

**Comment by acidmanifesto** [comment]
Currently at the moment we are discussing if this is either going to be considered a  core side issue or a module side issue.

**Comment by acidmanifesto** [comment]
at the moment if we dont have a coordinate we can not really confirm what the case may of been.

**Comment by adink1** [comment]
After teleporting to the prison, use a random instance to queue up, then it will be teleported to the instance, exit the instance and return to the prison, and return to the city to escape.

**Comment by Tony931023** [comment]
@acidmanifesto when you die in the icecrown area and release and use the teleport hack to the body 2 or 3 times in a row it crashes the server

**Comment by Tony931023** [comment]
if you are summoned out of prison and use speed hack, it also gives this crash

**Comment by acidmanifesto** [comment]
> After teleporting to the prison, use a random instance to queue up, then it will be teleported to the instance, exit the instance and return to the prison, and return to the city to escape.

return to the city? i am very confused with that set of instructions

**Comment by Tony931023** [comment]
I think it refers to using something described in this  #59 , to get out of prison

> > After teleporting to the prison, use a random instance to queue up, then it will be teleported to the instance, exit the instance and return to the prison, and return to the city to escape.
> 
> return to the city? i am very confused with that set of instructions

**Comment by acidmanifesto** [comment]
ok. so the issue with this, It isnt a thing with the module but the core's handling which leads to the assert. individual (if latency is involved of not i do not know) was most likely doing a teleport while being auto jailed and may of attempt durning the auto tele to the jail, durning which he hit a requirement which would not happen normally. He was loaded into a grid durning a remove from world (which is a remove from active grid), which lead to assert. I am not entirely certain how we can really go about in correcting this via module, maybe core, but i am still not able to find a consistent meathod in having this assert tossed up for me to hit it with debugger.

**Comment by acidmanifesto** [comment]
At the moment this will be closed as it is rules as a core problem and not a anticheat problem
