### ISSUE TITLE
killing the player when he is sent to jail is a bad idea

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/mod-anticheat#56]
killing the player when he is sent to jail is a bad idea, when you release the spirit you are sent out of jail and you can revive with the angel and use the teleport to a new area where you change the hearthstone

**Comment by acidmanifesto** [comment]
i will need to know a few things dealing with the player being killed as that isnt a feature in the anticheat module. I would need to know character level stat information and if there are modification, if not modification what cheat was used that lead to the jailing? was the jailing a automatic moderation or a .anticheat jail command?

**Comment by Tony931023** [comment]
https://user-images.githubusercontent.com/4868094/160242838-779e3d28-66da-41ce-8955-c0d59abb4cc2.mp4
