### ISSUE TITLE
freeze 

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/mod-anticheat#57]
when the player is sent to the prison and uses the unlock hack he can move around the room and is detected only if he uses speed hack or teleport

**Comment by Tony931023** [comment]
https://youtu.be/ngjqpA8aENI

**Comment by acidmanifesto** [comment]
Ill looking into the issues today. But anticheat module is designed to be used witg warden side by side as some hacks are not handle by the anticheat but thru warden packets.

**Comment by Tony931023** [comment]
I have the warden and anticheat active

**Comment by acidmanifesto** [comment]
> when the player is sent to the prison and uses the unlock hack he can move around the room and is detected only if he uses speed hack or teleport

is the ignore control hack detection turned on?

**Comment by Tony931023** [comment]
yes
