### ISSUE TITLE
Spam message swiping

### ISSUE THREAD

**Issue by mpfans** [azerothcore/mod-anticheat#61]
How to make these messages no longer visible on the console?

![image](https://user-images.githubusercontent.com/18187177/160318007-5fedbff0-c058-4364-ac7f-941c2a7117d9.png)

**Comment by Tony931023** [comment]
Anticheat.WriteLog = 0

**Comment by mpfans** [comment]
> Anticheat.WriteLog = 0

I need a log, but I don't want it to swipe the screen in the console

**Comment by Tony931023** [comment]
there is no file type log, it only shows in the console,

It would not hurt to implement the log in file (Suggestion)

**Comment by mpfans** [comment]
> there is no file type log, it only shows in the console,
> 
> It would not hurt to implement the log in file (Suggestion)

OK,tyvm

**Comment by acidmanifesto** [comment]
Just wanting to touch bases on this issue. Appender and loggers are currently not functioning correctly on azerothcore for modules. A issue was made and hopefully it will be looked into eventually.

**Comment by acidmanifesto** [comment]
marking this as core issue since there is a issue with azerothcore and logging from modules that was confirmed.
https://github.com/azerothcore/azerothcore-wotlk/issues/11297
