### ISSUE TITLE
False positives are serious

### ISSUE THREAD

**Issue by mpfans** [azerothcore/mod-anticheat#63]
### Current Behaviour

update to b78ce2399cdc338468ebe488374a41d661aa1f55

False positives are serious

https://youtu.be/BqUUJKWjy5w

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

b78ce2399cdc338468ebe488374a41d661aa1f55

### Operating system

ubuntu 20.04

**Comment by acidmanifesto** [comment]
Not all maps are littered like this one. but this is a rough look at what we are dealing with with alot of the spots with our maps.
For Each step you make over a tiny pothole that goes indefinitely deep, you end up getting flagged as you are in violation of the ignore z-axis.
![image](https://user-images.githubusercontent.com/16887899/163239418-41ebedb1-e81f-44b7-913c-a37cf50f313a.png)

**Comment by acidmanifesto** [comment]
@mpfans can u test with the new update [27f0772](https://github.com/azerothcore/mod-anticheat/commit/27f07720478abe54edcd5af92eb4a6fcbe23a326) and tell me if you are still getting false hits with z-axis?

**Comment by mpfans** [comment]
No false positives have been found yet

**Comment by acidmanifesto** [comment]
Thanks
