### ISSUE TITLE
is this mod can work? because is looks look not working for me, i used the newest version

### ISSUE THREAD

**Issue by 5266869** [azerothcore/mod-anticheat#64]
### Current Behaviour

is this mod can work? because is looks look not working for me, i used the newest version

### Expected Blizzlike Behaviour

.

### Steps to reproduce the problem

.

### AC rev. hash/commit

.

### Operating system

ubuntu 21

**Comment by Helias** [comment]
@acidmanifesto

**Comment by acidmanifesto** [comment]
Its working for me with the last test being about 12 hrs ago and works currently on CC. Ensure you do not have gm mod on. Gm's are exempt from the detection. Ensure your account is gm lvl 2 or 3 to use the commands in the wiki.

**Comment by acidmanifesto** [comment]
Please read the wiki for all thing cheat related and ensure conf is set up propperly. https://github.com/azerothcore/mod-anticheat/wiki

**Comment by Tony931023** [comment]
@5266869 
Working perfect in the latest revision of AC,
You should comment AC version you are using.
Check if your player is a GM and if you have enabled to detect GMs
Checking the x number of reports tells you the AntiHack.
Check if you are playing with a player (Account level 1) not GM, (Account level 2 or 3)

> ### more information is needed from the user
