### ISSUE TITLE
after i cheat , this also said i cheat when i donot .

### ISSUE THREAD

**Issue by 5266869** [azerothcore/mod-anticheat#66]
### Current Behaviour

i just set this conf:
Anticheat.KickPlayer = 1
Anticheat.ReportsForKick = 10

when i cheat ,it worked, i was been kicked.
but, after i cheat , it always kicked me , and i donot cheat.
it was also kicked me when i changed anthoer account.
i test this so many times, 
is this a bug or any other setting i need change it ?
thanks very much

### Expected Blizzlike Behaviour

.

### Steps to reproduce the problem

.

### AC rev. hash/commit

.

### Operating system

ubuntu 21

**Comment by Tony931023** [comment]
Show the logs that come out in the worldserver console (Anti Cheat.WriteLog = 1)

Do you have the latest version of AC updated? with the newly extracted map,vmap,mmap

try disabling Anticheat.DetectZaxisHack =1 if you don't have the above.

**Comment by 5266869** [comment]
AnticheatMgr:: Ignore Zaxis Hack detected player Kk (GUID Full: 0x000000000000000d Type: Player Low: 13)
AnticheatMgr:: Ignore Zaxis Hack detected player Kk (GUID Full: 0x000000000000000d Type: Player Low: 13)
AnticheatMgr:: Ignore Zaxis Hack detected player Kk (GUID Full: 0x000000000000000d Type: Player Low: 13)
AnticheatMgr:: Ignore Zaxis Hack detected player Kk (GUID Full: 0x000000000000000d Type: Player Low: 13)
AnticheatMgr:: Ignore Zaxis Hack detected player Kk (GUID Full: 0x000000000000000d Type: Player Low: 13)
AnticheatMgr:: Ignore Zaxis Hack detected player Kk (GUID Full: 0x000000000000000d Type: Player Low: 13)
AnticheatMgr:: Ignore Zaxis Hack detected player Kk (GUID Full: 0x000000000000000d Type: Player Low: 13)
AnticheatMgr:: Ignore Zaxis Hack detected player Kk (GUID Full: 0x000000000000000d Type: Player Low: 13)
AnticheatMgr:: Ignore Zaxis Hack detected player Kk (GUID Full: 0x000000000000000d Type: Player Low: 13)
AnticheatMgr:: Ignore Zaxis Hack detected player Kk (GUID Full: 0x000000000000000d Type: Player Low: 13)
Saving reports for 1 players.
AnticheatMgr:: Ignore Zaxis Hack detected player Kk (GUID Full: 0x000000000000000d Type: Player Low: 13)
AnticheatMgr:: Reports reached assigned threshhold and counteracted by kicking player Kk (GUID Full: 0x000000000000000d Type: Player Low: 13)


this is the logs , i just normal walk and jump 

my AC it is the  latest version and i used this https://github.com/wowgaming/client-data   AC data v13

**Comment by Tony931023** [comment]
disable Anticheat.DetectZaxisHack =0, 
those data files that you are currently using are out of date for the core, I recommend you use the map extractor and extract them all so that you have them updated

**Comment by 5266869** [comment]
OK，i will try it, thanks very much.

**Comment by acidmanifesto** [comment]
The z-axis detection is correct in the module but the core maps is full of micro potholes. See past exsisting issue with further details.
https://github.com/azerothcore/mod-anticheat/issues/63
