### ISSUE TITLE
Teleport Hack False positive when using flight master

### ISSUE THREAD

**Issue by wow-private-servers** [azerothcore/mod-anticheat#67]
### Current Behaviour

Teleport Hack False positive when using flight master

### Expected Blizzlike Behaviour

Should not trigger the teleport hack

### Steps to reproduce the problem

Take a flight path to anywhere and you'll trigger the teleport hack

### AC rev. hash/commit

lastest

### Operating system

Linux, Win 64

**Comment by acidmanifesto** [comment]
Issue was fixed two weeks ago. The issue was additional helpers needed in azerothcore. Please update azerothcore to the latest revision or to rev https://github.com/azerothcore/azerothcore-wotlk/pull/11277 at a minimal

**Comment by wow-private-servers** [comment]
Thanks for the info
