### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by mpfans** [azerothcore/mod-anticheat#70]
### Current Behaviour

When a player rides a flying mount and flies close to the water, a false positive will appear

https://youtu.be/eoCrEhfkhWI

Be sure to fly close to the water

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

1.Summon a flying mount
2.Fly close to the water

### AC rev. hash/commit

317f3ac963803a4b879fc82a5f3b7757abf70da3

### Operating system

ubuntu 20.04

**Comment by acidmanifesto** [comment]
What false positive detection is happening?

**Comment by mpfans** [comment]
![image](https://user-images.githubusercontent.com/18187177/166904756-4da98252-91ac-4472-9949-b60a74c21fe8.png)

Cast a spell 1706 on a player who is not GM,Then summon the flying mount and fly close to the water,will reappear

**Comment by mpfans** [comment]
![image](https://user-images.githubusercontent.com/18187177/166905852-bdcffb28-45b5-4d4f-b1ea-741c8a500b48.png)

**Comment by acidmanifesto** [comment]
We should have a cheat type in the server.log file, world console, or do a manticheat player on the character.

**Comment by acidmanifesto** [comment]
ok. looking over it a few times i see a hit for water walking which should be resolved now with [1d8c03f](https://github.com/azerothcore/mod-anticheat/commit/1d8c03f259b8acfd3020f620a351fa4c4f97f17d) of the module. 
Please confirm @mpfans for me

**Comment by acidmanifesto** [comment]
> ok, I will test it. tyvm 

Any results yet?

**Comment by mpfans** [comment]
tested,work now.
