### ISSUE TITLE
quest 10111 false positive

### ISSUE THREAD

**Issue by mpfans** [azerothcore/mod-anticheat#72]
### Current Behaviour

get quest 10111,and then click `Jump-a-tron 4000` false positive

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

1. `.go xyz -2430.580322 6887.100586 4.382977 530 `
2. `.quest a 10109`
3. `.quest c 10109`
4. `.quest a 10111`
5. Right click `Jump-a-tron 4000`

PS:Please do it in a non GM account

### AC rev. hash/commit

4c2cb8290458f3f237380b1c0664d53a5d6e88d7

### Operating system

ubuntu 20.04

**Comment by acidmanifesto** [comment]
Issue identified as gravity hack false hit.
Fix is pushed. Thank you for the report.
[a2729ba](https://github.com/azerothcore/mod-anticheat/commit/a2729ba8f619771b3476140a2c59a9c67bc14f13)
