### ISSUE TITLE
Upgrade to the latest, false positive

### ISSUE THREAD

**Issue by mpfans** [azerothcore/mod-anticheat#73]
### Current Behaviour

from 4c2cb8290458f3f237380b1c0664d53a5d6e88d7 update to bb0d175b151451f3ca4b20eb5029d26081e9ed56,more the false positive

https://youtu.be/qQ1u0WU_E0k

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

bb0d175b151451f3ca4b20eb5029d26081e9ed56

### Operating system

ubuntu 20.04

**Comment by acidmanifesto** [comment]
I need more information such as location and what cheat is showing up in the server.log file

**Comment by mpfans** [comment]
server.log no cheat log 

![image](https://user-images.githubusercontent.com/18187177/167636721-95276148-fd20-4fcb-a9f5-75f705fd7c29.png)

**Comment by mpfans** [comment]
> please try the latest [a2729ba](https://github.com/azerothcore/mod-anticheat/commit/a2729ba8f619771b3476140a2c59a9c67bc14f13) There was a SERIOUS over sight on my end that your other report lead me to discover. see if that fixes the issue.

ok... It's the peak time of online, and players are all doing raid

**Comment by acidmanifesto** [comment]
@mpfans also gm cmd .anticheat player gives you cheat report.
![image](https://user-images.githubusercontent.com/16887899/167638052-cdb27800-d094-41d1-9534-d163505a6368.png)
That will help alot as well

**Comment by mpfans** [comment]
![image](https://user-images.githubusercontent.com/18187177/167638931-29048ca3-6532-48b3-b6a3-b38c4d508812.png)

**Comment by acidmanifesto** [comment]
awsome. so its the telepane hack.
turn it off in conf and do a .reload conf
it should stop reporting for now til i figure out the issue

**Comment by acidmanifesto** [comment]
Still attempting to correct the issue with telepane hack detection. Please leave it off for the tume being.

**Comment by acidmanifesto** [comment]
@mpfans Can you please test [81f0dbf](https://github.com/azerothcore/mod-anticheat/commit/81f0dbfd81600fa895c658cf597487f5c17b6f89)

**Comment by mpfans** [comment]
![image](https://user-images.githubusercontent.com/18187177/167866311-9b07265c-ee3d-49f8-92fb-3686b39ceede.png)

**Comment by acidmanifesto** [comment]
Better solution will be pushed in 2 hrs
