### ISSUE TITLE
`Mine Sweeper` achievement process false positive

### ISSUE THREAD

**Issue by mpfans** [azerothcore/mod-anticheat#74]
### Current Behaviour

do `Mine Sweeper` achievement process false positive

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

1. `.go xyz 6042.642090 -728.950562 371.824280 571`
2. go the minefield

### AC rev. hash/commit

de22e25cb25b91e02e507d0d314fde709ef3e78e

### Operating system

ubuntu 20.04

**Comment by acidmanifesto** [comment]
confirm bug on my end. will look into today.

**Comment by acidmanifesto** [comment]
@mpfans please try [98e7294](https://github.com/azerothcore/mod-anticheat/commit/98e72947dad5aee713b92a2d81d28f997353c1b2) and let me know

**Comment by acidmanifesto** [comment]
Better solution will be pushed in 2 hrs

**Comment by acidmanifesto** [comment]
Please try [365c6f6](https://github.com/azerothcore/mod-anticheat/commit/365c6f6c6e7370f8361bfcf4a92a5decce59bc9b)
