### ISSUE TITLE
Ban-Time How change?

### ISSUE THREAD

**Issue by Awixs777** [azerothcore/mod-anticheat#76]
Good afternoon.

Tell me, please, where can I change the time for which a ban is issued? For now, it is permanent.

**Comment by acidmanifesto** [comment]
> Good afternoon.
> 
> Tell me, please, where can I change the time for which a ban is issued? For now, it is permanent.

https://github.com/azerothcore/mod-anticheat/blob/d528c4d62a71010bf5f50e543dd6f985c7e32a34/src/AnticheatMgr.cpp#L884

Change the 0s to what ever duration in seconds you want. anything 0s or negative is a permanent ban.
![image](https://user-images.githubusercontent.com/16887899/174412086-2176aace-bdb6-42c7-b381-c9d36749e844.png)
