### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Niceguy1337** [azerothcore/mod-anticheat#77]
### Current Behaviour

Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Nachricht		Siehe Deklaration von "Player"	modules	G:\WoW Server\AzerothCore\Core\src\server\game\Entities\Player\Player.h	1036	
Fehler	C2039	"CanTeleport" ist kein Member von "Player".	modules	G:\WoW Server\AzerothCore\Core\modules\mod-anticheat\src\AnticheatMgr.cpp	377	
Nachricht		Siehe Deklaration von "Player"	modules	G:\WoW Server\AzerothCore\Core\src\server\game\Entities\Player\Player.h	1036	
Fehler	C2039	"CanTeleport" ist kein Member von "Player".	modules	G:\WoW Server\AzerothCore\Core\modules\mod-anticheat\src\AnticheatMgr.cpp	399	
Nachricht		Siehe Deklaration von "Player"	modules	G:\WoW Server\AzerothCore\Core\src\server\game\Entities\Player\Player.h	1036	
Fehler	C2039	"SetCanTeleport" ist kein Member von "Player".	modules	G:\WoW Server\AzerothCore\Core\modules\mod-anticheat\src\AnticheatMgr.cpp	400	
Nachricht		Siehe Deklaration von "Player"	modules	G:\WoW Server\AzerothCore\Core\src\server\game\Entities\Player\Player.h	1036	
Fehler	C2039	"CanTeleport" ist kein Member von "Player".	modules	G:\WoW Server\AzerothCore\Core\modules\mod-anticheat\src\AnticheatMgr.cpp	403	
Nachricht		Siehe Deklaration von "Player"	modules	G:\WoW Server\AzerothCore\Core\src\server\game\Entities\Player\Player.h	1036	
Fehler	C2039	"CanTeleport" ist kein Member von "Player".	modules	G:\WoW Server\AzerothCore\Core\modules\mod-anticheat\src\AnticheatMgr.cpp	437	
Nachricht		Siehe Deklaration von "Player"	modules	G:\WoW Server\AzerothCore\Core\src\server\game\Entities\Player\Player.h	1036	
Fehler	C2039	"SetCanTeleport" ist kein Member von "Player".	modules	G:\WoW Server\AzerothCore\Core\modules\mod-anticheat\src\AnticheatMgr.cpp	438	
Nachricht		Siehe Deklaration von "Player"	modules	G:\WoW Server\AzerothCore\Core\src\server\game\Entities\Player\Player.h	1036	
Fehler	C2039	"CanTeleport" ist kein Member von "Player".	modules	G:\WoW Server\AzerothCore\Core\modules\mod-anticheat\src\AnticheatMgr.cpp	678	

### Expected Blizzlike Behaviour

Compile without errors

### Steps to reproduce the problem

Just Compile with newest Azerothcore

### AC rev. hash/commit

cd576790c9240717fe2e8bfe97c20b9c0c48b53a

### Operating system

Windows 10

**Comment by acidmanifesto** [comment]
Please update you core to the newest. you are missing the helpers that was implemented a long long time ago.
![image](https://user-images.githubusercontent.com/16887899/177214619-452d49a7-4a0a-4a93-bdc5-20756f1e319e.png)
