### ISSUE TITLE
Missing Config entrys

### ISSUE THREAD

**Issue by Niceguy1337** [azerothcore/mod-anticheat#78]
### Current Behaviour

Missing Config entrys
It spams the console

### Expected Blizzlike Behaviour

Anticheat.DetectGravityHack = 1
Anticheat.DetectZaxisHack = 1
Anticheat.IgnoreControlHack = 1
Anticheat.DetectTelePortHack = 1
Anticheat.AntiSwimHack = 1
Anticheat.KickPlayer = 1
Anticheat.JailPlayer = 1
Anticheat.ReportForBan = 1

### Steps to reproduce the problem

Start Server with anticheat module.
Wait until players playing at server.
Check console for missing config entrys.

### AC rev. hash/commit

145f81d40fff8ce033d3286c3f93a0294331b979

### Operating system

Windows 10

**Comment by acidmanifesto** [comment]
They are all present in the 
https://github.com/azerothcore/mod-anticheat/blob/master/conf/Anticheat.conf.dist

Be sure to follow the readme.md
I had zero issues with a clean install.![Screenshot_20220711-123614_GitHub.jpg](https://user-images.githubusercontent.com/16887899/178314088-ec29dc93-ac6e-48bd-aaec-8ae97a940536.jpg)
