### ISSUE TITLE
False reports

### ISSUE THREAD

**Issue by poszer** [azerothcore/mod-anticheat#8]
Testing it for more than 5 days. Too much false reports for players. 
If someone playing on high ms (laging), it will send too much reports, telling that a player is cheating.
I think it will be better to take out this module, since it can slow up core a lot while making this reports.
![screenshot_1](https://user-images.githubusercontent.com/41213210/46909975-f37ee580-cf3b-11e8-8911-6a8258945082.png)

**Comment by BarbzYHOOL** [comment]
Have you tried this conf option https://github.com/azerothcore/mod-anticheat/commit/a8166b05076652e86762b5afb01da9bb91b17cd0 ?
