### ISSUE TITLE
Feature: anti pass through closed door cheat and separate different cheat numbers

### ISSUE THREAD

**Issue by kissingers** [azerothcore/mod-anticheat#84]
### Describe your feature request or suggestion in detail

There is a kind of self patch MPQ in the game,  with which can pass through those doors that are not open (not walls) , is it can increase the judgment of this kind of hacker cheat?
In addition, for each type of hacker cheat, is it possible to set a separate threshold for the number of times for this type of cheat?

**Comment by acidmanifesto** [comment]
At the moment we **DO NOT** have a detection for **no clip hacking** as it is called.  
Its when the player is able to walk thru wmo and select gameobjects.

When detection is figured out it will be its own count collumn and conf detection.

It is on a to list. It's a bit complicated in setting up a detection for it at the moment with out it causing false flags.
