### ISSUE TITLE
When a player is stuck in a corner the knockback will error report.

### ISSUE THREAD

**Issue by kissingers** [azerothcore/mod-anticheat#85]
### Current Behaviour

Sorry I'm going to mention another bug, but this is really in the game often misjudged, when a player is stuck in a corner, then the creature knock back the player, because in corner the player will not knock back, so very fast error report numbers add for the knockback hack.
[2022-08-19 22-20-36.zip](https://github.com/azerothcore/mod-anticheat/files/9382928/2022-08-19.22-20-36.zip)
![1660919456144](https://user-images.githubusercontent.com/33601959/185641559-a1fa9dd1-b1a3-4ad0-903d-6bbff141ce8c.png)
.

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

Anchila's many bee can knockback player, where it is good to be tested.

### AC rev. hash/commit

N/A

### Operating system

debian 11 x64

**Comment by acidmanifesto** [comment]
Hey @kissingers , thank you for the report. Unfortunately i wont be able to look at it until my replacement parts come in for my laptop. I will should be back looking at things in the next 72hrs.

**Comment by acidmanifesto** [comment]
@kissingers looking at the video, was there any modded items or gm cmd in use when you recorded that?

**Comment by kissingers** [comment]
I only chang my HP to max so will not be killed by the bee

**Comment by acidmanifesto** [comment]
> I only chang my HP to max so will not be killed by the bee

this anticheat is not really designed to work with modifications out side of stock. 
increasing your HP to that extreme amount will cause issues with that check as the most a player will ever get knocked back in a corner situation before dying is atleast two times. This report is not valid.

**Comment by kissingers** [comment]
OK, but sometimes the tank will be stuck in the corner to resist the monster, and healers are healing him, this condition is also valid.
