### ISSUE TITLE
Flyhack ignoring

### ISSUE THREAD

**Issue by Awixs777** [azerothcore/mod-anticheat#87]
### Current Behaviour

Hello again. When using the flight hack, the anti-cheat does not respond. Any reaction appears when using the speed hack and flying hack together. Latest revision of anti-cheat and AC.
Used cheats: http://cheaters.at.ua/load/cheats/wow/simplefly/5-1-0-167
![td7wlDbmim4](https://user-images.githubusercontent.com/47874183/186236817-0a473bc9-6e76-4ec9-bf66-b1f6c06a1083.jpg)
.

### Expected Blizzlike Behaviour

-

### Steps to reproduce the problem

-

### AC rev. hash/commit

-

### Operating system

Win10

**Comment by acidmanifesto** [comment]
works fine testing on a level 0 gm account.
![image](https://user-images.githubusercontent.com/16887899/186283670-0d921031-5406-415d-89fe-fcc6c825b8be.png)
Ensure .gm on is not being used.
Ensure conf settings are correct with recommended settings on the [wiki](https://github.com/azerothcore/mod-anticheat/wiki#conf)
Ensure Anticheat is turned on in the conf and appropiate settings set for fly hack detection, if testing on GM account then ensure gm account detection is turned on as well:
```
Anticheat.Enabled = 1
Anticheat.EnabledOnGmAccounts = 1
Anticheat.DetectFlyHack = 1
Anticheat.StricterFlyHackCheck = 1
```

**Comment by Awixs777** [comment]
@acidmanifesto I do not know what to say. Completely reinstalled anti-cheat, rebuilt the kernel. When the fly hack is activated, the anti-cheat does not react in any way, the account is level 0. Only if you turn on the speed hack, there will be triggers. Prompt, with what it can be connected?
Video: https://drive.google.com/file/d/1Kwo5gcOKXDoO4Cdx0M228iTDmHrqLS12/view?usp=sharing

**Comment by acidmanifesto** [comment]
> @acidmanifesto I do not know what to say. Completely reinstalled anti-cheat, rebuilt the kernel. When the fly hack is activated, the anti-cheat does not react in any way, the account is level 0. Only if you turn on the speed hack, there will be triggers. Prompt, with what it can be connected?
> Used cheats "SimpleFly": https://disk.yandex.ru/d/moHwPg6G3Ng86u
> Video: https://drive.google.com/file/d/1Kwo5gcOKXDoO4Cdx0M228iTDmHrqLS12/view?usp=sharing
> 

Thank you for the links. I will reopen while i re-evaulate.

**Comment by acidmanifesto** [comment]
@Awixs777 so surprisingly, even though this is called simple fly, it isnt a fly hack at all but a jump hack.
I am accessing further for detection and will update.

**Comment by Awixs777** [comment]
@acidmanifesto It works now. Thanks a lot.

**Comment by Awixs777** [comment]
@acidmanifesto Hello. After the latest jump hack update, a lot of false positives appeared. Look please.
![Screenshot_1](https://user-images.githubusercontent.com/47874183/186845869-f625af89-06a1-4bb8-96ee-f6448e0ac019.png)

**Comment by acidmanifesto** [comment]
can you give me the .gps of the location  please @Awixs777

**Comment by Awixs777** [comment]
@acidmanifesto  .go xyz 530.789124 550.055969 770.276367 601
here are the coordinates. But false positives occur in any other places. Video example:
https://drive.google.com/file/d/1BcvMoVn2CrskPDfVio4dxpWXFmtmCoIX/view?usp=sharing

**Comment by acidmanifesto** [comment]
> @acidmanifesto .go xyz 530.789124 550.055969 770.276367 601 here are the coordinates. But false positives occur in any other places. Video example: https://drive.google.com/file/d/1BcvMoVn2CrskPDfVio4dxpWXFmtmCoIX/view?usp=sharing

thank you. give me a bit to evaulate and i will ping you once i am done.

**Comment by acidmanifesto** [comment]
> @acidmanifesto .go xyz 530.789124 550.055969 770.276367 601 here are the coordinates, It's enough just to jump off the bridge (sometimes a couple of times). But false positives occur in any other places. Video example: https://drive.google.com/file/d/1BcvMoVn2CrskPDfVio4dxpWXFmtmCoIX/view?usp=sharing

please test https://github.com/azerothcore/mod-anticheat/commit/ab65943a81c073dc91aee4e8e3c6597ee45cd0d7

**Comment by Awixs777** [comment]
@acidmanifesto It works better, false positives have become harder to trigger. But they still remain. Video example.
https://drive.google.com/file/d/1CI3cW3eWQbgRohXwVFrkrG6AeEdZZPb8/view?usp=sharing

**Comment by acidmanifesto** [comment]
> @acidmanifesto It works better, false positives have become harder to trigger. But they still remain. Video example. https://drive.google.com/file/d/1CI3cW3eWQbgRohXwVFrkrG6AeEdZZPb8/view?usp=sharing

is that a custom zone? regardless if it is or isnt. i will have to find a simular spot to simulate that false hit in stock build.

**Comment by Awixs777** [comment]
@acidmanifesto Okay, here. The back of a building on General Motors Island. The triggers seem to occur when the camera rotates with the character.
Video: https://drive.google.com/file/d/1x3p7uyA7ZLMFY2zjapt6ALUQ5yVxuwB_/view?usp=sharing

**Comment by acidmanifesto** [comment]
So what i can tell from the video you provided. When you jump off the top of hte stairs, you briefly go over the platforms edge.  
![image](https://user-images.githubusercontent.com/16887899/186948897-6015f1b5-bfff-4f30-8337-a5741aa6eec7.png)

With that barrier i can look at in gm island. As for custom zones, i can't really provide too much for custom maps due to mmaps and vmaps being specially build, infact we have a warning about custom maps on the wiki for the z-axis hack detection.

The camera rotation hits can be easily addressed. I will have to go over the building in gm island in debugger to address further.

**Comment by acidmanifesto** [comment]
@Awixs777 please try https://github.com/azerothcore/mod-anticheat/commit/0f7dbc1ba6060cc55340b6db78aedefdd0420629

**Comment by Awixs777** [comment]
@acidmanifesto  Thanks, seems to be fine now. I tested for about 5 minutes on the GM island and also in our custom area, both with and without camera rotation. I was unable to trigger an anti-cheat trigger.

**Comment by acidmanifesto** [comment]
> @acidmanifesto  Thanks, seems to be fine now. I tested for about 5 minutes on the GM island and also in our custom area, both with and without camera rotation. I was unable to trigger an anti-cheat trigger.

Thats good to hear. Thank you for your time.
