### ISSUE TITLE
Here is the crash of your anti-cheat, I don't know why, but I have already made files specifically for you!

### ISSUE THREAD

**Issue by MegaserverRU** [azerothcore/mod-anticheat#93]
### Current Behaviour

Here is the crash of your anti-cheat, I don't know why, but I have already made files specifically for you!
[Crashes.zip](https://github.com/azerothcore/mod-anticheat/files/9468834/Crashes.zip)

### Expected Blizzlike Behaviour

I registered an account created a character turned on an anti cheat and flooded the server with a crash

### Source

I registered an account created a character turned on an anti cheat and flooded the server with a crash

### Steps to reproduce the problem

I registered an account created a character turned on an anti cheat and flooded the server with a crash

### Extra Notes

no

### AC rev. hash/commit

I registered an account created a character turned on an anti cheat and flooded the server with a crash

### Operating system

Windows 7 x64

### Custom changes or Modules

Modules: mod-1v1-arena, mod-ah-bot, mod-anticheat, mod-cfbg, mod-congrats-on-level, mod-custom-login, mod-guildhouse, mod-learn-spells,  mod-npc-buffer, mod-npc-enchanter, mod-pocket-portal, mod-premium, mod-transmog, mod-who-logged,

**Comment by acidmanifesto** [comment]
What is exactly "and flooded the server with a crash" mean? I see nothing in the crash log dealing with the anticheat.
